# Winterfell for Alacritty
# ~/.config/alacritty/theme.yml
colors:
  primary:
    background: '#1e282e'
    foreground: '#a0b4c1'
    dim_foreground: '#628397'
    bright_foreground: '#cad5dc'
  cursor:
    text: '#1e282e'
    cursor: '#8ccf7e'
  vi_mode_cursor:
    text: '#1e282e'
    cursor: '#8ccf7e'
  search:
    matches:
      foreground: '#2b3a43'
      background: '#ad8bee'
    focused_match:
      foreground: '#ad8bee'
      background: '#2b3a43'
  hints:
    start:
      foreground: '#2b3a43'
      background: '#d8ce91'
    end:
      foreground: '#d8ce91'
      background: '#2b3a43'
  line_indicator:
    foreground: None
    background: None
  footer_bar:
    foreground: '#2b3a43'
    background: '#ad8bee'
  selection:
    text: '#a0b4c1'
    background: '#32434d'
  normal:
    black: '#394c58'
    red: '#e86a6f'
    green: '#8ccf7e'
    yellow: '#d8ce91'
    blue: '#709ad2'
    magenta: '#d076b9'
    cyan: '#70d8ca'
    white: '#cad5dc'
  bright:
    black: '#394c58'
    red: '#e86a6f'
    green: '#8ccf7e'
    yellow: '#d8ce91'
    blue: '#709ad2'
    magenta: '#d076b9'
    cyan: '#70d8ca'
    white: '#cad5dc'
    