#!/bin/fish

# Install basic packages
sudo pacman -S --noconfirm --needed base-devel git fish rustup

# Install rustup toolchain
echo "Installing rustup with its stable toolchain ..."
rustup install stable
rustup default stable

sleep 1

# Install Paru
if which paru
  echo "[DONE] Paru has been detected."
else
  echo "Installing paru ..."
  git clone https://aur.archlinux.org/paru.git
  pushd paru
  makepkg -si --noconfirm
  popd
  rm -rf paru
end

sleep 1

echo "Refreshing repositories ..."
paru -Syy --noconfirm
paru -Sy --noconfirm archlinux-keyring

sleep 1

echo "Installing necessary packages ..."
paru -S --noconfirm --needed \
  alacritty \
  base-devel \
  btop \
  breeze-snow-cursor-theme \
  calc \
  clang \
  curl \
  chromium \
  docker \
  docker-compose \
  docker-machine \
  dunst \
  eww-wayland-git \
  fd \
  firefox-developer-edition \
  fish \
  fnm-bin \
  hyprland-git \
  hyprpaper-git \
  git \
  glfw-wayland \
  go \
  golangci-lint \
  grim \
  gtk-layer-shell \
  gtk3 \
  gtk4 \
  imagemagick \
  imv \
  jq \
  lf \
  luacheck \
  man \
  neovim \
  papirus-icon-theme \
  pdfjs \
  pipewire \
  polkit-kde-agent \
  python-adblock \
  python-pip \
  qt5-wayland \
  qt6-wayland \
  qutebrowser \
  ripgrep \
  rofi-lbonn-wayland-git \
  rsync \
  rustup \
  sddm \
  sddm-sugar-candy-git \
  slurp \
  starship \
  swayidle \
  swaylock-effects-git \
  stylua \
  tree \
  ttf-roboto \
  unzip \
  xdg-desktop-portal-hyprland-git \
  xdg-utils \
  xdg-user-dirs \
  vscode \
  wf-recorder \
  wlr-randr \
  wlsunset \
  wl-clipboard \
  wireplumber \
  xorg-xwayland \
  xorg-xlsclients \
  zathura \
  zathura-pdf-poppler

sleep 1
